### ISSUE TITLE
How to use with Arabic language

### ISSUE THREAD

**Issue by zicas2000** [Enigo/UnityEasyLocalization#1]
How to make text displayed correctly in Arabic as it goes from left to right while it supposed to be displayed from right to left

**Comment by Enigo** [comment]
Hey @zicas2000 
Please, take a look at the [Advanced localization techniques](https://github.com/Enigo/UnityAdvancedLocalization/blob/master/Assets/Scripts/LangResolver.cs) and the tutorial on [Medium](https://levelup.gitconnected.com/unity-advanced-localization-802cb954ca16)

It's not directly there but the code is easily extendable. 
Let me give you a direction:
You should add a new field, let's say `bool leftToRight` to `LangData` inner class of above-mentioned tutorial. Then, you should set it to true for the required languages and apply it to the Text UI object whenever you resolve locales.

Let me know if you have any further questions.
